// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_STAAR_RCPPEXPORTS_H_GEN_
#define RCPP_STAAR_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace STAAR {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("STAAR", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("STAAR", "_STAAR_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in STAAR");
            }
        }
    }

    inline double Bisection(arma::vec egvalues, double q, double xmin, double xmax) {
        typedef SEXP(*Ptr_Bisection)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_Bisection p_Bisection = NULL;
        if (p_Bisection == NULL) {
            validateSignature("double(*Bisection)(arma::vec,double,double,double)");
            p_Bisection = (Ptr_Bisection)R_GetCCallable("STAAR", "_STAAR_Bisection");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Bisection(Shield<SEXP>(Rcpp::wrap(egvalues)), Shield<SEXP>(Rcpp::wrap(q)), Shield<SEXP>(Rcpp::wrap(xmin)), Shield<SEXP>(Rcpp::wrap(xmax)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double Bisection_Binary_SPA(arma::vec muhat, arma::vec G, double q, double xmin, double xmax, double tol) {
        typedef SEXP(*Ptr_Bisection_Binary_SPA)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Bisection_Binary_SPA p_Bisection_Binary_SPA = NULL;
        if (p_Bisection_Binary_SPA == NULL) {
            validateSignature("double(*Bisection_Binary_SPA)(arma::vec,arma::vec,double,double,double,double)");
            p_Bisection_Binary_SPA = (Ptr_Bisection_Binary_SPA)R_GetCCallable("STAAR", "_STAAR_Bisection_Binary_SPA");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Bisection_Binary_SPA(Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)), Shield<SEXP>(Rcpp::wrap(q)), Shield<SEXP>(Rcpp::wrap(xmin)), Shield<SEXP>(Rcpp::wrap(xmax)), Shield<SEXP>(Rcpp::wrap(tol)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double CCT_pval(arma::vec x, arma::vec weights) {
        typedef SEXP(*Ptr_CCT_pval)(SEXP,SEXP);
        static Ptr_CCT_pval p_CCT_pval = NULL;
        if (p_CCT_pval == NULL) {
            validateSignature("double(*CCT_pval)(arma::vec,arma::vec)");
            p_CCT_pval = (Ptr_CCT_pval)R_GetCCallable("STAAR", "_STAAR_CCT_pval");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_CCT_pval(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(weights)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K(double x, arma::vec egvalues) {
        typedef SEXP(*Ptr_K)(SEXP,SEXP);
        static Ptr_K p_K = NULL;
        if (p_K == NULL) {
            validateSignature("double(*K)(double,arma::vec)");
            p_K = (Ptr_K)R_GetCCallable("STAAR", "_STAAR_K");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(egvalues)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K1(double x, arma::vec egvalues, double q) {
        typedef SEXP(*Ptr_K1)(SEXP,SEXP,SEXP);
        static Ptr_K1 p_K1 = NULL;
        if (p_K1 == NULL) {
            validateSignature("double(*K1)(double,arma::vec,double)");
            p_K1 = (Ptr_K1)R_GetCCallable("STAAR", "_STAAR_K1");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K1(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(egvalues)), Shield<SEXP>(Rcpp::wrap(q)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K1_Binary_SPA(double x, arma::vec muhat, arma::vec G, double q) {
        typedef SEXP(*Ptr_K1_Binary_SPA)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_K1_Binary_SPA p_K1_Binary_SPA = NULL;
        if (p_K1_Binary_SPA == NULL) {
            validateSignature("double(*K1_Binary_SPA)(double,arma::vec,arma::vec,double)");
            p_K1_Binary_SPA = (Ptr_K1_Binary_SPA)R_GetCCallable("STAAR", "_STAAR_K1_Binary_SPA");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K1_Binary_SPA(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)), Shield<SEXP>(Rcpp::wrap(q)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K1_Binary_SPA_alt(double x, arma::vec muhat, arma::vec G, double q) {
        typedef SEXP(*Ptr_K1_Binary_SPA_alt)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_K1_Binary_SPA_alt p_K1_Binary_SPA_alt = NULL;
        if (p_K1_Binary_SPA_alt == NULL) {
            validateSignature("double(*K1_Binary_SPA_alt)(double,arma::vec,arma::vec,double)");
            p_K1_Binary_SPA_alt = (Ptr_K1_Binary_SPA_alt)R_GetCCallable("STAAR", "_STAAR_K1_Binary_SPA_alt");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K1_Binary_SPA_alt(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)), Shield<SEXP>(Rcpp::wrap(q)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K2(double x, arma::vec egvalues) {
        typedef SEXP(*Ptr_K2)(SEXP,SEXP);
        static Ptr_K2 p_K2 = NULL;
        if (p_K2 == NULL) {
            validateSignature("double(*K2)(double,arma::vec)");
            p_K2 = (Ptr_K2)R_GetCCallable("STAAR", "_STAAR_K2");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K2(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(egvalues)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K2_Binary_SPA(double x, arma::vec muhat, arma::vec G) {
        typedef SEXP(*Ptr_K2_Binary_SPA)(SEXP,SEXP,SEXP);
        static Ptr_K2_Binary_SPA p_K2_Binary_SPA = NULL;
        if (p_K2_Binary_SPA == NULL) {
            validateSignature("double(*K2_Binary_SPA)(double,arma::vec,arma::vec)");
            p_K2_Binary_SPA = (Ptr_K2_Binary_SPA)R_GetCCallable("STAAR", "_STAAR_K2_Binary_SPA");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K2_Binary_SPA(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K2_Binary_SPA_alt(double x, arma::vec muhat, arma::vec G) {
        typedef SEXP(*Ptr_K2_Binary_SPA_alt)(SEXP,SEXP,SEXP);
        static Ptr_K2_Binary_SPA_alt p_K2_Binary_SPA_alt = NULL;
        if (p_K2_Binary_SPA_alt == NULL) {
            validateSignature("double(*K2_Binary_SPA_alt)(double,arma::vec,arma::vec)");
            p_K2_Binary_SPA_alt = (Ptr_K2_Binary_SPA_alt)R_GetCCallable("STAAR", "_STAAR_K2_Binary_SPA_alt");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K2_Binary_SPA_alt(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K_Binary_SPA(double x, arma::vec muhat, arma::vec G) {
        typedef SEXP(*Ptr_K_Binary_SPA)(SEXP,SEXP,SEXP);
        static Ptr_K_Binary_SPA p_K_Binary_SPA = NULL;
        if (p_K_Binary_SPA == NULL) {
            validateSignature("double(*K_Binary_SPA)(double,arma::vec,arma::vec)");
            p_K_Binary_SPA = (Ptr_K_Binary_SPA)R_GetCCallable("STAAR", "_STAAR_K_Binary_SPA");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K_Binary_SPA(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double K_Binary_SPA_alt(double x, arma::vec muhat, arma::vec G) {
        typedef SEXP(*Ptr_K_Binary_SPA_alt)(SEXP,SEXP,SEXP);
        static Ptr_K_Binary_SPA_alt p_K_Binary_SPA_alt = NULL;
        if (p_K_Binary_SPA_alt == NULL) {
            validateSignature("double(*K_Binary_SPA_alt)(double,arma::vec,arma::vec)");
            p_K_Binary_SPA_alt = (Ptr_K_Binary_SPA_alt)R_GetCCallable("STAAR", "_STAAR_K_Binary_SPA_alt");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_K_Binary_SPA_alt(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double NR_Binary_SPA(arma::vec muhat, arma::vec G, double q, double init, double tol, int max_iter) {
        typedef SEXP(*Ptr_NR_Binary_SPA)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_NR_Binary_SPA p_NR_Binary_SPA = NULL;
        if (p_NR_Binary_SPA == NULL) {
            validateSignature("double(*NR_Binary_SPA)(arma::vec,arma::vec,double,double,double,int)");
            p_NR_Binary_SPA = (Ptr_NR_Binary_SPA)R_GetCCallable("STAAR", "_STAAR_NR_Binary_SPA");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_NR_Binary_SPA(Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)), Shield<SEXP>(Rcpp::wrap(q)), Shield<SEXP>(Rcpp::wrap(init)), Shield<SEXP>(Rcpp::wrap(tol)), Shield<SEXP>(Rcpp::wrap(max_iter)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double Saddle(double q, arma::vec egvalues) {
        typedef SEXP(*Ptr_Saddle)(SEXP,SEXP);
        static Ptr_Saddle p_Saddle = NULL;
        if (p_Saddle == NULL) {
            validateSignature("double(*Saddle)(double,arma::vec)");
            p_Saddle = (Ptr_Saddle)R_GetCCallable("STAAR", "_STAAR_Saddle");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Saddle(Shield<SEXP>(Rcpp::wrap(q)), Shield<SEXP>(Rcpp::wrap(egvalues)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double Saddle_Binary_SPA(double q, arma::vec muhat, arma::vec G, double tol, int max_iter, bool lower) {
        typedef SEXP(*Ptr_Saddle_Binary_SPA)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Saddle_Binary_SPA p_Saddle_Binary_SPA = NULL;
        if (p_Saddle_Binary_SPA == NULL) {
            validateSignature("double(*Saddle_Binary_SPA)(double,arma::vec,arma::vec,double,int,bool)");
            p_Saddle_Binary_SPA = (Ptr_Saddle_Binary_SPA)R_GetCCallable("STAAR", "_STAAR_Saddle_Binary_SPA");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Saddle_Binary_SPA(Shield<SEXP>(Rcpp::wrap(q)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)), Shield<SEXP>(Rcpp::wrap(tol)), Shield<SEXP>(Rcpp::wrap(max_iter)), Shield<SEXP>(Rcpp::wrap(lower)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline double Saddle_Binary_SPA_Bisection(double q, arma::vec muhat, arma::vec G, double tol, int max_iter, double xmin, double xmax, bool lower) {
        typedef SEXP(*Ptr_Saddle_Binary_SPA_Bisection)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Saddle_Binary_SPA_Bisection p_Saddle_Binary_SPA_Bisection = NULL;
        if (p_Saddle_Binary_SPA_Bisection == NULL) {
            validateSignature("double(*Saddle_Binary_SPA_Bisection)(double,arma::vec,arma::vec,double,int,double,double,bool)");
            p_Saddle_Binary_SPA_Bisection = (Ptr_Saddle_Binary_SPA_Bisection)R_GetCCallable("STAAR", "_STAAR_Saddle_Binary_SPA_Bisection");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Saddle_Binary_SPA_Bisection(Shield<SEXP>(Rcpp::wrap(q)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)), Shield<SEXP>(Rcpp::wrap(tol)), Shield<SEXP>(Rcpp::wrap(max_iter)), Shield<SEXP>(Rcpp::wrap(xmin)), Shield<SEXP>(Rcpp::wrap(xmax)), Shield<SEXP>(Rcpp::wrap(lower)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

    inline bool check_is_na(double x) {
        typedef SEXP(*Ptr_check_is_na)(SEXP);
        static Ptr_check_is_na p_check_is_na = NULL;
        if (p_check_is_na == NULL) {
            validateSignature("bool(*check_is_na)(double)");
            p_check_is_na = (Ptr_check_is_na)R_GetCCallable("STAAR", "_STAAR_check_is_na");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_check_is_na(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<bool >(rcpp_result_gen);
    }

    inline arma::vec goldenSectionSearchForSignChange(double a, double b, arma::vec muhat, arma::vec G, double q, double tol, int max_iter) {
        typedef SEXP(*Ptr_goldenSectionSearchForSignChange)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_goldenSectionSearchForSignChange p_goldenSectionSearchForSignChange = NULL;
        if (p_goldenSectionSearchForSignChange == NULL) {
            validateSignature("arma::vec(*goldenSectionSearchForSignChange)(double,double,arma::vec,arma::vec,double,double,int)");
            p_goldenSectionSearchForSignChange = (Ptr_goldenSectionSearchForSignChange)R_GetCCallable("STAAR", "_STAAR_goldenSectionSearchForSignChange");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_goldenSectionSearchForSignChange(Shield<SEXP>(Rcpp::wrap(a)), Shield<SEXP>(Rcpp::wrap(b)), Shield<SEXP>(Rcpp::wrap(muhat)), Shield<SEXP>(Rcpp::wrap(G)), Shield<SEXP>(Rcpp::wrap(q)), Shield<SEXP>(Rcpp::wrap(tol)), Shield<SEXP>(Rcpp::wrap(max_iter)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline bool haveSameSign(double a, double b) {
        typedef SEXP(*Ptr_haveSameSign)(SEXP,SEXP);
        static Ptr_haveSameSign p_haveSameSign = NULL;
        if (p_haveSameSign == NULL) {
            validateSignature("bool(*haveSameSign)(double,double)");
            p_haveSameSign = (Ptr_haveSameSign)R_GetCCallable("STAAR", "_STAAR_haveSameSign");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_haveSameSign(Shield<SEXP>(Rcpp::wrap(a)), Shield<SEXP>(Rcpp::wrap(b)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<bool >(rcpp_result_gen);
    }

    inline List matrix_flip(arma::mat G) {
        typedef SEXP(*Ptr_matrix_flip)(SEXP);
        static Ptr_matrix_flip p_matrix_flip = NULL;
        if (p_matrix_flip == NULL) {
            validateSignature("List(*matrix_flip)(arma::mat)");
            p_matrix_flip = (Ptr_matrix_flip)R_GetCCallable("STAAR", "_STAAR_matrix_flip");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_matrix_flip(Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

    inline arma::mat matrix_impute(arma::mat G) {
        typedef SEXP(*Ptr_matrix_impute)(SEXP);
        static Ptr_matrix_impute p_matrix_impute = NULL;
        if (p_matrix_impute == NULL) {
            validateSignature("arma::mat(*matrix_impute)(arma::mat)");
            p_matrix_impute = (Ptr_matrix_impute)R_GetCCallable("STAAR", "_STAAR_matrix_impute");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_matrix_impute(Shield<SEXP>(Rcpp::wrap(G)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

}

#endif // RCPP_STAAR_RCPPEXPORTS_H_GEN_
