// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_STAAR_H_GEN_
#define RCPP_STAAR_H_GEN_

#include "STAAR_RcppExports.h"

#endif // RCPP_STAAR_H_GEN_
