# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Bisection <- function(egvalues, q, xmin, xmax) {
    .Call(`_STAAR_Bisection`, egvalues, q, xmin, xmax)
}

CCT_pval <- function(x, weights) {
    .Call(`_STAAR_CCT_pval`, x, weights)
}

Indiv_Score_Test <- function(G, X, working, sigma, fam, residuals) {
    .Call(`_STAAR_Indiv_Score_Test`, G, X, working, sigma, fam, residuals)
}

Indiv_Score_Test_SMMAT <- function(G, P, residuals) {
    .Call(`_STAAR_Indiv_Score_Test_SMMAT`, G, P, residuals)
}

Indiv_Score_Test_SMMAT_sparse <- function(G, Sigma_i, Sigma_iX, cov, residuals) {
    .Call(`_STAAR_Indiv_Score_Test_SMMAT_sparse`, G, Sigma_i, Sigma_iX, cov, residuals)
}

Indiv_Score_Test_SMMAT_sparse_cond <- function(G, Sigma_i, Sigma_iX, cov, X_adj, residuals) {
    .Call(`_STAAR_Indiv_Score_Test_SMMAT_sparse_cond`, G, Sigma_i, Sigma_iX, cov, X_adj, residuals)
}

K <- function(x, egvalues) {
    .Call(`_STAAR_K`, x, egvalues)
}

K1 <- function(x, egvalues, q) {
    .Call(`_STAAR_K1`, x, egvalues, q)
}

K2 <- function(x, egvalues) {
    .Call(`_STAAR_K2`, x, egvalues)
}

STAAR_O <- function(G, X, working, sigma, fam, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_STAAR_STAAR_O`, G, X, working, sigma, fam, residuals, weights_B, weights_S, weights_A, mac, mac_thres)
}

STAAR_O_SMMAT <- function(G, P, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_STAAR_STAAR_O_SMMAT`, G, P, residuals, weights_B, weights_S, weights_A, mac, mac_thres)
}

STAAR_O_SMMAT_sparse <- function(G, Sigma_i, Sigma_iX, cov, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_STAAR_STAAR_O_SMMAT_sparse`, G, Sigma_i, Sigma_iX, cov, residuals, weights_B, weights_S, weights_A, mac, mac_thres)
}

STAAR_O_SMMAT_sparse_cond <- function(G, Sigma_i, Sigma_iX, cov, X_adj, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_STAAR_STAAR_O_SMMAT_sparse_cond`, G, Sigma_i, Sigma_iX, cov, X_adj, residuals, weights_B, weights_S, weights_A, mac, mac_thres)
}

Saddle <- function(q, egvalues) {
    .Call(`_STAAR_Saddle`, q, egvalues)
}

matrix_flip <- function(G) {
    .Call(`_STAAR_matrix_flip`, G)
}

matrix_impute <- function(G) {
    .Call(`_STAAR_matrix_impute`, G)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_STAAR_RcppExport_registerCCallable', PACKAGE = 'STAAR')
})
