# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matsp <- function(G) {
    .Call(`_STAAR_matsp`, G)
}

matrix_flip <- function(G) {
    .Call(`_STAAR_matrix_flip`, G)
}

STAAR_O <- function(G, X, working, sigma, fam, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_STAAR_STAAR_O`, G, X, working, sigma, fam, residuals, weights_B, weights_S, weights_A, mac, mac_thres)
}

STAAR_O_SMMAT <- function(G, P, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_STAAR_STAAR_O_SMMAT`, G, P, residuals, weights_B, weights_S, weights_A, mac, mac_thres)
}

STAAR_O_SMMAT_sparse <- function(G, Sigma_i, Sigma_iX, cov, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_STAAR_STAAR_O_SMMAT_sparse`, G, Sigma_i, Sigma_iX, cov, residuals, weights_B, weights_S, weights_A, mac, mac_thres)
}

